version: "3.9"

services:
  postgres_db:
    image: postgres:alpine
    container_name: postgres_docker
    ports:
      - "5432:5432"
    volumes:
      - .pg/:/var/lib/postgresql/data/
    env_file:
      - .env
  samsung_server:
    build:
      dockerfile: Dockerfile
      context: .
    image: samsung_server
    container_name: samsung_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    env_file:
      - .env

